
import { SkillDefinition } from './types';

export const SKILL_DEFINITIONS: SkillDefinition[] = [
  { id: 'iniciativa', name: 'Iniciativa', parentAttr: 'AGILIDADE', ratio: 2, description: 'Capacidade de agir rapidamente em situações de perigo.' },
  { id: 'controleMuscular', name: 'Controle Muscular', parentAttr: 'FORÇA', ratio: 2, description: 'Domínio sobre o próprio corpo para feitos de precisão.' },
  { id: 'carregamentoPeso', name: 'Carregamento de Peso', parentAttr: 'FORÇA', ratio: 2, description: 'Força para transportar grandes cargas.' },
  { id: 'intimidade', name: 'Intimidação', parentAttr: 'FORÇA', ratio: 2, description: 'Uso de presença para impor medo e respeito.' },
  { id: 'meditacao', name: 'Meditação', parentAttr: 'INTELIGÊNCIA', ratio: 2, description: 'Foco interior para recuperar energia.' },
  { id: 'oficioCriacao', name: 'Ofício Criação', parentAttr: 'INTELIGÊNCIA', ratio: 2, description: 'Habilidade de fabricar itens.' },
  { id: 'sabedoria', name: 'Sabedoria', parentAttr: 'INTELIGÊNCIA', ratio: 2, description: 'Conhecimento prático e espiritual.' },
  { id: 'cura', name: 'Cura', parentAttr: 'INTELIGÊNCIA', ratio: 2, description: 'Técnicas de tratar ferimentos.' },
  { id: 'arremessar', name: 'Arremessar', parentAttr: 'AGILIDADE', ratio: 2, description: 'Precisão ao lançar objetos.' },
  { id: 'atletismo', name: 'Atletismo', parentAttr: 'AGILIDADE', ratio: 2, description: 'Força física aplicada em corrida e salto.' },
  { id: 'sobrevivencia', name: 'Sobrevivência', parentAttr: 'AGILIDADE', ratio: 2, description: 'Conhecimento da natureza para caçar.' },
  { id: 'acrobacia', name: 'Acrobacia', parentAttr: 'AGILIDADE', ratio: 2, description: 'Agilidade para saltos e movimentos evasivos.' },
  { id: 'sorte', name: 'Sorte', parentAttr: 'ACURACIDADE', ratio: 2, description: 'Capacidade de escapar de perigos improváveis.' },
  { id: 'estrategia', name: 'Estratégia', parentAttr: 'ACURACIDADE', ratio: 2, description: 'Planejamento para vencer batalhas.' },
  { id: 'resAlcool', name: 'Resistência a Álcool', parentAttr: 'VIDA', ratio: 3, description: 'Suportar os efeitos da embriaguez.' },
  { id: 'resVeneno', name: 'Resistência a Veneno', parentAttr: 'VIDA', ratio: 3, description: 'Força vital contra toxinas.' },
  { id: 'resDoencas', name: 'Resistência a Doenças', parentAttr: 'VIDA', ratio: 3, description: 'Imunidade natural contra enfermidades.' },
  { id: 'resHemorragia', name: 'Resistência a Hemorragia', parentAttr: 'VIDA', ratio: 3, description: 'Capacidade de manter-se firme após ferimentos.' },
  { id: 'resRespiratoria', name: 'Resistência Respiratória', parentAttr: 'VIDA', ratio: 3, description: 'Fôlego para ambientes sufocantes.' },
  { id: 'intimidadePoder', name: 'Intimidação de Poder', parentAttr: 'MANA', ratio: 3, description: 'Uso de força bruta ou mágica para subjugar.' },
  { id: 'concentracao', name: 'Concentração', parentAttr: 'MANA', ratio: 3, description: 'Foco absoluto sob pressão.' },
  { id: 'manipulacaoEnergia', name: 'Manipulação de Energia', parentAttr: 'MANA', ratio: 3, description: 'Controle de forças místicas.' },
  { id: 'percepcao', name: 'Percepção', parentAttr: 'EVASÃO', ratio: 3, description: 'Atenção aos detalhes e sons sutis.' },
  { id: 'fuga', name: 'Fuga', parentAttr: 'EVASÃO', ratio: 3, description: 'Habilidade de escapar de prisões.' },
  { id: 'detArmadilhas', name: 'Detecção de Armadilhas', parentAttr: 'EVASÃO', ratio: 3, description: 'Identificar mecanismos ocultos.' },
  { id: 'vigilancia', name: 'Vigilância', parentAttr: 'EVASÃO', ratio: 3, description: 'Manter-se atento por longos períodos.' },
  { id: 'detPerigo', name: 'Detectar Perigo', parentAttr: 'EVASÃO', ratio: 3, description: 'Instinto aguçado que alerta ameaças.' },
  { id: 'intuicao', name: 'Intuição', parentAttr: 'EVASÃO', ratio: 3, description: 'Julgamento rápido baseado em sentimentos.' },
  { id: 'obterInformacao', name: 'Obter Informação', parentAttr: 'FURTIVIDADE', ratio: 3, description: 'Extrair dados de pessoas e locais.' },
  { id: 'ladinagem', name: 'Ladinagem', parentAttr: 'FURTIVIDADE', ratio: 3, description: 'Arte de abrir fechaduras e agir furtivamente.' },
  { id: 'carisma', name: 'Carisma', parentAttr: 'FURTIVIDADE', ratio: 3, description: 'Presença magnética que inspira confiança.' },
  { id: 'atuacao', name: 'Atuação', parentAttr: 'FURTIVIDADE', ratio: 3, description: 'Talento para interpretar papéis.' },
  { id: 'diplomacia', name: 'Diplomacia', parentAttr: 'FURTIVIDADE', ratio: 3, description: 'Habilidade de negociar e convencer.' },
  { id: 'enganacao', name: 'Enganação', parentAttr: 'FURTIVIDADE', ratio: 3, description: 'Uso de mentiras e truques.' },
  { id: 'furtividadeSkill', name: 'Furtividade', parentAttr: 'FURTIVIDADE', ratio: 4, description: 'Capacidade de se mover sem ser visto.' },
  { id: 'bloquear', name: 'Bloquear', parentAttr: 'DEFESA FÍSICA', ratio: 4, description: 'Intercepção de ataques inimigos.' },
  { id: 'defenderAliado', name: 'Defender Aliado', parentAttr: 'DEFESA FÍSICA', ratio: 4, description: 'Proteger um companheiro.' },
  { id: 'coragem', name: 'Coragem', parentAttr: 'DEFESA FÍSICA', ratio: 4, description: 'Resistência ao pânico e medo.' },
  { id: 'idMagia', name: 'Identificar Magia', parentAttr: 'DEFESA MÁGICA', ratio: 4, description: 'Reconhecimento de fenômenos arcanos.' },
  { id: 'resSono', name: 'Resistência a Sono', parentAttr: 'DEFESA MÁGICA', ratio: 4, description: 'Resistir a indução mágica de sono.' },
  { id: 'resCharme', name: 'Resistência a Charme', parentAttr: 'DEFESA MÁGICA', ratio: 4, description: 'Força mental contra seduções mágicas.' },
  { id: 'resPsiquica', name: 'Resistência Psíquica', parentAttr: 'DEFESA MÁGICA', ratio: 4, description: 'Defesa contra ataques mentais.' },
  { id: 'resFeiticos', name: 'Resistência a Feitiços', parentAttr: 'DEFESA MÁGICA', ratio: 4, description: 'Suportar magias ofensivas.' },
  { id: 'resIlusoes', name: 'Resistência a Ilusões', parentAttr: 'DEFESA MÁGICA', ratio: 4, description: 'Distinguir realidade de enganos mágicos.' },
  { id: 'resMaldições', name: 'Resistência a Maldições', parentAttr: 'DEFESA MÁGICA', ratio: 4, description: 'Força espiritual contra efeitos sombrios.' },
  { id: 'resSobrenatural', name: 'Resistência Sobrenatural', parentAttr: 'DEFESA MÁGICA', ratio: 4, description: 'Defesa contra forças além da compreensão.' },
];
